package graphique;

import classes.FeuilleDessin;
import classes.ListeFormes;
import classes.Point;
import java.awt.Color;
import static java.awt.Color.*;
import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 * Classe qui gere le Menu et ses actions
 * @author As'
 */
public class Contenu extends javax.swing.JFrame {
    
    private FeuilleDessin feuille;
    private Palette c;
    private Point pp;
    private Color couleur; 
    
    /**
     * Creates new form NewJFrame
     * @param p
     * @param choix
     */  
    public Contenu(Point p, Palette choix) {
        pp = p;
        c = choix;
        this.setLayout(null);
        feuille = new FeuilleDessin(pp,400,400);
        this.add(feuille);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        ButtonRect = new javax.swing.JToggleButton();
        ButtonCercle = new javax.swing.JToggleButton();
        ButtonTrig = new javax.swing.JToggleButton();
        ButtonRemplir = new javax.swing.JToggleButton();
        ButtonPattern = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        ButtonEff = new javax.swing.JToggleButton();
        ButtonNoir = new javax.swing.JToggleButton();
        ButtonBlanc = new javax.swing.JToggleButton();
        ButtonRouge = new javax.swing.JToggleButton();
        ButtonVert = new javax.swing.JToggleButton();
        ButtonBlue = new javax.swing.JToggleButton();
        ButtonJaune = new javax.swing.JToggleButton();
        ButtonDef = new javax.swing.JToggleButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jLabel4 = new javax.swing.JLabel();
        LabelTaille = new javax.swing.JLabel();
        spinnerLargeur = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        spinnerHauteur = new javax.swing.JSpinner();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jLabel2 = new javax.swing.JLabel();
        spinnerPression = new javax.swing.JSpinner();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        ButtonVider = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MFichier = new javax.swing.JMenu();
        MenuNouv = new javax.swing.JMenuItem();
        MenuOuvrir = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        MenuEnreg = new javax.swing.JMenuItem();
        MenuEnrSous = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuQuitter = new javax.swing.JMenuItem();
        MEdition = new javax.swing.JMenu();
        MenuAnnuler = new javax.swing.JMenuItem();
        MenuRep = new javax.swing.JMenuItem();
        MDoc = new javax.swing.JMenu();
        MenuProp = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItemVIder = new javax.swing.JMenuItem();
        MFormes = new javax.swing.JMenu();
        MenuRect = new javax.swing.JMenuItem();
        MenuEllipse = new javax.swing.JMenuItem();
        MenTrig = new javax.swing.JMenuItem();
        MenuRemp = new javax.swing.JMenuItem();
        MCouleurs = new javax.swing.JMenu();
        MenuEfface = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuNoir = new javax.swing.JMenuItem();
        jMenuBlanc = new javax.swing.JMenuItem();
        jMenuRouge = new javax.swing.JMenuItem();
        jMenuVert = new javax.swing.JMenuItem();
        MenuBleu = new javax.swing.JMenuItem();
        MenuJaune = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuDef = new javax.swing.JMenuItem();
        MPropos = new javax.swing.JMenu();
        jMenuAprop = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem9.setText("jMenuItem9");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        buttonGroup1.add(ButtonRect);
        ButtonRect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classes/images/rectangle.png"))); // NOI18N
        ButtonRect.setBorderPainted(false);
        ButtonRect.setFocusable(false);
        ButtonRect.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonRect.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonRect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRectActionPerformed(evt);
            }
        });
        jToolBar1.add(ButtonRect);

        buttonGroup1.add(ButtonCercle);
        ButtonCercle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classes/images/ellipse.png"))); // NOI18N
        ButtonCercle.setBorderPainted(false);
        ButtonCercle.setFocusable(false);
        ButtonCercle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonCercle.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonCercle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCercleActionPerformed(evt);
            }
        });
        jToolBar1.add(ButtonCercle);

        buttonGroup1.add(ButtonTrig);
        ButtonTrig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classes/images/triangle.png"))); // NOI18N
        ButtonTrig.setBorderPainted(false);
        ButtonTrig.setFocusable(false);
        ButtonTrig.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonTrig.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonTrig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTrigActionPerformed(evt);
            }
        });
        jToolBar1.add(ButtonTrig);

        buttonGroup1.add(ButtonRemplir);
        ButtonRemplir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classes/images/fill.png"))); // NOI18N
        ButtonRemplir.setBorderPainted(false);
        ButtonRemplir.setFocusable(false);
        ButtonRemplir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonRemplir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonRemplir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRemplirActionPerformed(evt);
            }
        });
        jToolBar1.add(ButtonRemplir);

        buttonGroup1.add(ButtonPattern);
        ButtonPattern.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classes/images/pattern.png"))); // NOI18N
        ButtonPattern.setBorderPainted(false);
        ButtonPattern.setFocusable(false);
        ButtonPattern.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonPattern.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(ButtonPattern);

        jSeparator1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jSeparator1.setOpaque(true);
        jToolBar1.add(jSeparator1);

        buttonGroup3.add(ButtonEff);
        ButtonEff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classes/images/eraser.png"))); // NOI18N
        ButtonEff.setBorderPainted(false);
        ButtonEff.setFocusable(false);
        ButtonEff.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonEff.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonEff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEffActionPerformed(evt);
            }
        });
        jToolBar1.add(ButtonEff);

        buttonGroup3.add(ButtonNoir);
        ButtonNoir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classes/images/black.png"))); // NOI18N
        ButtonNoir.setBorderPainted(false);
        ButtonNoir.setFocusable(false);
        ButtonNoir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonNoir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonNoir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNoirActionPerformed(evt);
            }
        });
        jToolBar1.add(ButtonNoir);

        buttonGroup3.add(ButtonBlanc);
        ButtonBlanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classes/images/white.png"))); // NOI18N
        ButtonBlanc.setBorderPainted(false);
        ButtonBlanc.setFocusable(false);
        ButtonBlanc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonBlanc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonBlanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBlancActionPerformed(evt);
            }
        });
        jToolBar1.add(ButtonBlanc);

        buttonGroup3.add(ButtonRouge);
        ButtonRouge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classes/images/red.png"))); // NOI18N
        ButtonRouge.setBorderPainted(false);
        ButtonRouge.setFocusable(false);
        ButtonRouge.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonRouge.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonRouge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRougeActionPerformed(evt);
            }
        });
        jToolBar1.add(ButtonRouge);

        buttonGroup3.add(ButtonVert);
        ButtonVert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classes/images/green.png"))); // NOI18N
        ButtonVert.setBorderPainted(false);
        ButtonVert.setFocusable(false);
        ButtonVert.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonVert.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonVert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVertActionPerformed(evt);
            }
        });
        jToolBar1.add(ButtonVert);

        buttonGroup3.add(ButtonBlue);
        ButtonBlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classes/images/blue.png"))); // NOI18N
        ButtonBlue.setBorderPainted(false);
        ButtonBlue.setFocusable(false);
        ButtonBlue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonBlue.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBlueActionPerformed(evt);
            }
        });
        jToolBar1.add(ButtonBlue);

        buttonGroup3.add(ButtonJaune);
        ButtonJaune.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classes/images/yellow.png"))); // NOI18N
        ButtonJaune.setBorderPainted(false);
        ButtonJaune.setFocusable(false);
        ButtonJaune.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonJaune.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonJaune.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonJauneActionPerformed(evt);
            }
        });
        jToolBar1.add(ButtonJaune);

        buttonGroup3.add(ButtonDef);
        ButtonDef.setText("Definir...");
        ButtonDef.setFocusable(false);
        ButtonDef.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonDef.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonDef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDefActionPerformed(evt);
            }
        });
        jToolBar1.add(ButtonDef);

        jSeparator2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator2.setEnabled(false);
        jSeparator2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jToolBar1.add(jSeparator2);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classes/images/size.png"))); // NOI18N
        jToolBar1.add(jLabel4);

        LabelTaille.setText("Taille ");
        jToolBar1.add(LabelTaille);

        spinnerLargeur.setToolTipText("");
        spinnerLargeur.setPreferredSize(new java.awt.Dimension(5, 29));
        spinnerLargeur.setValue(20);
        spinnerLargeur.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerLargeurStateChanged(evt);
            }
        });
        jToolBar1.add(spinnerLargeur);

        jLabel1.setText(" x ");
        jToolBar1.add(jLabel1);

        spinnerHauteur.setToolTipText("20");
        spinnerHauteur.setPreferredSize(new java.awt.Dimension(5, 20));
        spinnerHauteur.setValue(20);
        spinnerHauteur.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerHauteurStateChanged(evt);
            }
        });
        jToolBar1.add(spinnerHauteur);
        jToolBar1.add(jSeparator3);

        jLabel2.setText(" Pression : ");
        jToolBar1.add(jLabel2);

        spinnerPression.setPreferredSize(new java.awt.Dimension(5, 20));
        spinnerPression.setValue(255);
        spinnerPression.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerPressionStateChanged(evt);
            }
        });
        jToolBar1.add(spinnerPression);
        jToolBar1.add(jSeparator4);

        ButtonVider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classes/images/clear.png"))); // NOI18N
        ButtonVider.setFocusable(false);
        ButtonVider.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonVider.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ButtonVider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonViderActionPerformed(evt);
            }
        });
        jToolBar1.add(ButtonVider);

        jLabel3.setText("Vider");
        jToolBar1.add(jLabel3);

        MFichier.setText("Fichier");

        MenuNouv.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        MenuNouv.setText("Nouveau...");
        MenuNouv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuNouvActionPerformed(evt);
            }
        });
        MFichier.add(MenuNouv);

        MenuOuvrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        MenuOuvrir.setText("Ouvrir...");
        MenuOuvrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOuvrirActionPerformed(evt);
            }
        });
        MFichier.add(MenuOuvrir);
        MFichier.add(jSeparator5);

        MenuEnreg.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        MenuEnreg.setText("Enregistrer");
        MFichier.add(MenuEnreg);

        MenuEnrSous.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuEnrSous.setText("Enregistrer sous...");
        MenuEnrSous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEnrSousActionPerformed(evt);
            }
        });
        MFichier.add(MenuEnrSous);
        MFichier.add(jSeparator6);

        jMenuQuitter.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuQuitter.setText("Quitter");
        jMenuQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuQuitterActionPerformed(evt);
            }
        });
        MFichier.add(jMenuQuitter);

        jMenuBar1.add(MFichier);

        MEdition.setText("Edition");

        MenuAnnuler.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        MenuAnnuler.setText("Annuler");
        MenuAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAnnulerActionPerformed(evt);
            }
        });
        MEdition.add(MenuAnnuler);

        MenuRep.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        MenuRep.setText("Repeter");
        MenuRep.setEnabled(false);
        MenuRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRepActionPerformed(evt);
            }
        });
        MEdition.add(MenuRep);

        jMenuBar1.add(MEdition);

        MDoc.setText("Document");

        MenuProp.setText("Propriete...");
        MenuProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPropActionPerformed(evt);
            }
        });
        MDoc.add(MenuProp);
        MDoc.add(jSeparator7);

        jMenuItemVIder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classes/images/clear.png"))); // NOI18N
        jMenuItemVIder.setText("Vider");
        jMenuItemVIder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVIderActionPerformed(evt);
            }
        });
        MDoc.add(jMenuItemVIder);

        jMenuBar1.add(MDoc);

        MFormes.setText("Formes");

        MenuRect.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        MenuRect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classes/images/rectangle.png"))); // NOI18N
        MenuRect.setText("Rectangle");
        MenuRect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRectActionPerformed(evt);
            }
        });
        MFormes.add(MenuRect);

        MenuEllipse.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        MenuEllipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classes/images/ellipse.png"))); // NOI18N
        MenuEllipse.setText("Ellipse");
        MenuEllipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEllipseActionPerformed(evt);
            }
        });
        MFormes.add(MenuEllipse);

        MenTrig.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        MenTrig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classes/images/triangle.png"))); // NOI18N
        MenTrig.setText("Triangle");
        MenTrig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenTrigActionPerformed(evt);
            }
        });
        MFormes.add(MenTrig);

        MenuRemp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_MASK));
        MenuRemp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classes/images/fill.png"))); // NOI18N
        MenuRemp.setText("Remplissage");
        MenuRemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRempActionPerformed(evt);
            }
        });
        MFormes.add(MenuRemp);

        jMenuBar1.add(MFormes);

        MCouleurs.setText("Couleurs");

        MenuEfface.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_0, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuEfface.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classes/images/eraser.png"))); // NOI18N
        MenuEfface.setText("Efface");
        MCouleurs.add(MenuEfface);
        MCouleurs.add(jSeparator8);

        jMenuNoir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuNoir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classes/images/black.png"))); // NOI18N
        jMenuNoir.setText("Noir");
        jMenuNoir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNoirActionPerformed(evt);
            }
        });
        MCouleurs.add(jMenuNoir);

        jMenuBlanc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuBlanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classes/images/white.png"))); // NOI18N
        jMenuBlanc.setText("Blanc");
        jMenuBlanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBlancActionPerformed(evt);
            }
        });
        MCouleurs.add(jMenuBlanc);

        jMenuRouge.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuRouge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classes/images/red.png"))); // NOI18N
        jMenuRouge.setText("Rouge");
        jMenuRouge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRougeActionPerformed(evt);
            }
        });
        MCouleurs.add(jMenuRouge);

        jMenuVert.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuVert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classes/images/green.png"))); // NOI18N
        jMenuVert.setText("Vert");
        jMenuVert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVertActionPerformed(evt);
            }
        });
        MCouleurs.add(jMenuVert);

        MenuBleu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuBleu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classes/images/blue.png"))); // NOI18N
        MenuBleu.setText("Bleu");
        MenuBleu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBleuActionPerformed(evt);
            }
        });
        MCouleurs.add(MenuBleu);

        MenuJaune.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_6, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MenuJaune.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classes/images/yellow.png"))); // NOI18N
        MenuJaune.setText("Jaune");
        MenuJaune.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuJauneActionPerformed(evt);
            }
        });
        MCouleurs.add(MenuJaune);
        MCouleurs.add(jSeparator9);

        jMenuDef.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_9, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuDef.setText("Definir...");
        jMenuDef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDefActionPerformed(evt);
            }
        });
        MCouleurs.add(jMenuDef);

        jMenuBar1.add(MCouleurs);

        MPropos.setText("?");

        jMenuAprop.setText("A Propos");
        jMenuAprop.setInheritsPopupMenu(true);
        jMenuAprop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuApropActionPerformed(evt);
            }
        });
        MPropos.add(jMenuAprop);

        jMenuBar1.add(MPropos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1278, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 554, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuNouvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuNouvActionPerformed
        feuille.clear();
    }//GEN-LAST:event_MenuNouvActionPerformed

    private void MenuOuvrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOuvrirActionPerformed
        JFrame cadre = new JFrame();
        JFileChooser ouvrir = new javax.swing.JFileChooser();
        cadre.setSize(500, 400);
        cadre.add(ouvrir);
        cadre.setVisible(true);
    }//GEN-LAST:event_MenuOuvrirActionPerformed

    private void jMenuItemVIderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVIderActionPerformed
        feuille.clear();
    }//GEN-LAST:event_jMenuItemVIderActionPerformed

    private void MenuEllipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEllipseActionPerformed
        ButtonCercle.doClick();
    }//GEN-LAST:event_MenuEllipseActionPerformed

    private void jMenuNoirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNoirActionPerformed
        couleur = black;
        pp.setCouleur(couleur);
        feuille.selection(pp);
    }//GEN-LAST:event_jMenuNoirActionPerformed

    private void jMenuDefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDefActionPerformed
        feuille.choisirCouleur(2);
    }//GEN-LAST:event_jMenuDefActionPerformed

    private void jMenuApropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuApropActionPerformed
        JFrame cadre = new JFrame("A Propos");
        Info aPropos = new Info();
        cadre.setSize(520, 185);
        cadre.add(aPropos);
        cadre.setVisible(true);
        cadre.setResizable(false);
        cadre.setLocationRelativeTo(jFrame1);
        
    }//GEN-LAST:event_jMenuApropActionPerformed

    private void MenuEnrSousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEnrSousActionPerformed

    }//GEN-LAST:event_MenuEnrSousActionPerformed

    private void ButtonJauneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonJauneActionPerformed
        couleur = yellow;
        pp.setCouleur(couleur);
        feuille.selection(pp);
    }//GEN-LAST:event_ButtonJauneActionPerformed

    private void MenuRempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRempActionPerformed
        ButtonRemplir.doClick(); 
    }//GEN-LAST:event_MenuRempActionPerformed

    private void ButtonRemplirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRemplirActionPerformed
        feuille.setCouleur(couleur);
        feuille.remplir(pp.getCouleur());
    }//GEN-LAST:event_ButtonRemplirActionPerformed

    private void ButtonBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBlueActionPerformed
        couleur = blue;
        pp.setCouleur(couleur);
        feuille.selection(pp);
    }//GEN-LAST:event_ButtonBlueActionPerformed

    private void ButtonVertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVertActionPerformed
        couleur = green;
        pp.setCouleur(couleur);
        feuille.selection(pp);
    }//GEN-LAST:event_ButtonVertActionPerformed

    private void ButtonRougeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRougeActionPerformed
        couleur = red;
        pp.setCouleur(couleur);
        feuille.selection(pp);
    }//GEN-LAST:event_ButtonRougeActionPerformed

    private void ButtonBlancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBlancActionPerformed
        couleur = white;
        pp.setCouleur(couleur);
        feuille.selection(pp);
    }//GEN-LAST:event_ButtonBlancActionPerformed

    private void ButtonNoirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNoirActionPerformed
        couleur = black;
        pp.setCouleur(couleur);
        feuille.selection(pp);
    }//GEN-LAST:event_ButtonNoirActionPerformed

    private void jMenuQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuQuitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuQuitterActionPerformed

    private void ButtonViderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonViderActionPerformed
       feuille.clear();
    }//GEN-LAST:event_ButtonViderActionPerformed

    private void MenuPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPropActionPerformed
        Propriete prop = new Propriete(feuille, c);
        prop.setVisible(true);
        prop.setLocationRelativeTo(jFrame1);
    }//GEN-LAST:event_MenuPropActionPerformed

    private void spinnerLargeurStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerLargeurStateChanged
        int info = Integer.parseInt(spinnerLargeur.getValue().toString());
        pp.setLargeur(info);
    }//GEN-LAST:event_spinnerLargeurStateChanged

    private void spinnerHauteurStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerHauteurStateChanged
        int info = Integer.parseInt(spinnerHauteur.getValue().toString());
        pp.setHauteur(info);
    }//GEN-LAST:event_spinnerHauteurStateChanged

    private void spinnerPressionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerPressionStateChanged
        int info = Integer.parseInt(spinnerPression.getValue().toString());
        pp.setDonnees(info);
    }//GEN-LAST:event_spinnerPressionStateChanged

    private void ButtonDefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDefActionPerformed
        feuille.choisirCouleur(2);
    }//GEN-LAST:event_ButtonDefActionPerformed

    private void ButtonEffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEffActionPerformed
        pp.setCouleur(feuille.getCouleur());
    }//GEN-LAST:event_ButtonEffActionPerformed

    private void ButtonTrigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTrigActionPerformed
        pp.setForme(ListeFormes.TRIANGLE);
    }//GEN-LAST:event_ButtonTrigActionPerformed

    private void ButtonRectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRectActionPerformed
        pp.setForme(ListeFormes.CARRE);
    }//GEN-LAST:event_ButtonRectActionPerformed

    private void ButtonCercleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCercleActionPerformed
        pp.setForme(ListeFormes.CERCLE);
    }//GEN-LAST:event_ButtonCercleActionPerformed

    private void MenuRectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRectActionPerformed
        ButtonRect.doClick(); 
    }//GEN-LAST:event_MenuRectActionPerformed

    private void MenTrigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenTrigActionPerformed
        ButtonTrig.doClick();
    }//GEN-LAST:event_MenTrigActionPerformed

    private void jMenuBlancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBlancActionPerformed
        ButtonBlanc.doClick();
    }//GEN-LAST:event_jMenuBlancActionPerformed

    private void jMenuRougeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRougeActionPerformed
        ButtonRouge.doClick();
    }//GEN-LAST:event_jMenuRougeActionPerformed

    private void jMenuVertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVertActionPerformed
        ButtonVert.doClick();
    }//GEN-LAST:event_jMenuVertActionPerformed

    private void MenuBleuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBleuActionPerformed
        ButtonBlue.doClick();
    }//GEN-LAST:event_MenuBleuActionPerformed

    private void MenuJauneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuJauneActionPerformed
        ButtonJaune.doClick();
    }//GEN-LAST:event_MenuJauneActionPerformed

    private void MenuRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuRepActionPerformed

    private void MenuAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAnnulerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuAnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
              // new Contenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ButtonBlanc;
    private javax.swing.JToggleButton ButtonBlue;
    private javax.swing.JToggleButton ButtonCercle;
    private javax.swing.JToggleButton ButtonDef;
    private javax.swing.JToggleButton ButtonEff;
    private javax.swing.JToggleButton ButtonJaune;
    private javax.swing.JToggleButton ButtonNoir;
    private javax.swing.JToggleButton ButtonPattern;
    private javax.swing.JToggleButton ButtonRect;
    private javax.swing.JToggleButton ButtonRemplir;
    private javax.swing.JToggleButton ButtonRouge;
    private javax.swing.JToggleButton ButtonTrig;
    private javax.swing.JToggleButton ButtonVert;
    private javax.swing.JButton ButtonVider;
    private javax.swing.JLabel LabelTaille;
    private javax.swing.JMenu MCouleurs;
    private javax.swing.JMenu MDoc;
    private javax.swing.JMenu MEdition;
    private javax.swing.JMenu MFichier;
    private javax.swing.JMenu MFormes;
    private javax.swing.JMenu MPropos;
    private javax.swing.JMenuItem MenTrig;
    private javax.swing.JMenuItem MenuAnnuler;
    private javax.swing.JMenuItem MenuBleu;
    private javax.swing.JMenuItem MenuEfface;
    private javax.swing.JMenuItem MenuEllipse;
    private javax.swing.JMenuItem MenuEnrSous;
    private javax.swing.JMenuItem MenuEnreg;
    private javax.swing.JMenuItem MenuJaune;
    private javax.swing.JMenuItem MenuNouv;
    private javax.swing.JMenuItem MenuOuvrir;
    private javax.swing.JMenuItem MenuProp;
    private javax.swing.JMenuItem MenuRect;
    private javax.swing.JMenuItem MenuRemp;
    private javax.swing.JMenuItem MenuRep;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuAprop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuBlanc;
    private javax.swing.JMenuItem jMenuDef;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemVIder;
    private javax.swing.JMenuItem jMenuNoir;
    private javax.swing.JMenuItem jMenuQuitter;
    private javax.swing.JMenuItem jMenuRouge;
    private javax.swing.JMenuItem jMenuVert;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JSpinner spinnerHauteur;
    private javax.swing.JSpinner spinnerLargeur;
    private javax.swing.JSpinner spinnerPression;
    // End of variables declaration//GEN-END:variables

}
